kind: pipeline
type: docker
name: default

steps:
- name: go_test
  image: golang:1.20
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  commands:
  - go get -d -t ./...
  # - go build
  # - go test -cover
  - go test -v ./...
  when:
    branch:
    - master
    event:
    - push
    - pull_request